# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidcard',
            name='barcode',
            field=models.CharField(default=payment.models.uuidGeneratorPrepaid, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card_number',
            field=models.CharField(default=payment.models.uuidGeneratorUserCard, max_length=16, unique=True),
        ),
    ]
