# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170725_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
