# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidcard',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
