# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_prepaidcard_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidcard',
            name='user_card',
        ),
    ]
