# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170726_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(to='payment.Product'),
        ),
    ]
