# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_prepaidcard_user_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='img/itugnu.png', null=True, upload_to=''),
        ),
    ]
