# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/itugnu.png', null=True, upload_to='img/uploaded'),
        ),
    ]
