# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_vendor_vendor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'name'},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'brand')]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Vendor'),
        ),
    ]
