# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20170730_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='images/itugnu.png', null=True, upload_to='images'),
        ),
    ]
