# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20170730_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('product', 'vendor')]),
        ),
    ]
