# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20170731_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded'),
        ),
    ]
