# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20170731_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
